global:
  scrape_interval: 5s # Fast for lab environments

scrape_configs:
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal' allows the container to see the app running on your Mac host
      - targets: ['host.docker.internal:8082']

  - job_name: 'redpanda'
    metrics_path: '/public_metrics'
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']