name: Order Service CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'order-service/**'       # <--- ONLY trigger on changes here
      - '.github/workflows/order-service-ci.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'order-service/**'
      - '.github/workflows/order-service-ci.yml'

# concurrency:
#   group: "gh-pages-deploy"
#   cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to push to gh-pages branch
    # Set the default working directory for all 'run' commands in this job
    defaults:
      run:
        working-directory: ./order-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test Order Service
      run: mvn clean verify --batch-mode -ntp

    # - name: Fetch Allure history
    #   uses: actions/checkout@v4
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: gh-pages
    #     path: gh-pages
    #
    # - name: Generate Allure Report
    #   uses: simple-elf/allure-report-action@master
    #   if: always()
    #   with:
    #     allure_results: order-service/target/allure-results
    #     allure_history: allure-history
    #     keep_reports: 20
    #
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v4
    #   if: always()
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: gh-pages
    #     publish_dir: allure-history
    #     keep_files: true                     # <--- Prevents deleting the inventory report
    #     destination_dir: order-service       # <--- Puts the report in its own folder